name: "🐛 Bug Report"
description: Report an issue or possible bug
title: "[BUG]: "
labels: ["🐛 bug: unconfirmed"]

body:
  - type: markdown
    attributes:
      value: |
        ## Quick Bug Form
        Please fill out this form as completely as possible.

  - type: dropdown
    id: browser
    attributes:
      label: Select Your Browser
      options:
        - Google Chrome
        - Mozilla Firefox
        - Microsoft Edge
        - Safari
        - Opera
        - Other
    validations:
      required: true

  - type: input
    id: other_browser
    attributes:
      label: If you selected "Other", specify the browser here
      placeholder: Other browser
    validations:
      required: false

  - type: input
    id: browser_version
    attributes:
      label: What is your browser version?
      placeholder: Browser version
    validations:
      required: true

  - type: textarea
    id: bug_description
    attributes:
      label: Describe the Bug
      description: Include steps to reproduce the issue
    validations:
      required: true

  - type: textarea
    id: to_reproduce
    attributes:
      label: Steps to Reproduce
      description: Provide detailed steps to replicate the issue
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected_behavior
    attributes:
      label: Expected Behavior
      description: What you expected to happen
    validations:
      required: false

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain the problem
      placeholder: Drag and drop images here or paste links

  - type: textarea
    id: additional_context
    attributes:
      label: Additional Context
      description: Add any other context about the problem here
      placeholder: Environment details, logs, etc.
