name: CI

on:
  push:
    branches: ["main"]
    paths-ignore:
      - ".gitignore"
      - ".prettierignore"
      - ".prettierrc"
      - ".github/ISSUE_TEMPLATE/**"
      - "public/**"
      - "LICENSE"
      - "README.md"
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: "Build"
    runs-on: ubuntu-latest
    timeout-minutes: 10

    env:
      NEXT_PUBLIC_BASE_URL: ${{ vars.NEXT_PUBLIC_BASE_URL }}
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      RESEND_API_KEY: ${{ secrets.RESEND_API_KEY }}
      RESEND_DOMAIN: ${{ secrets.RESEND_DOMAIN }}
      BETTER_AUTH_SECRET: ${{ secrets.BETTER_AUTH_SECRET }}
      BETTER_AUTH_URL: ${{ secrets.BETTER_AUTH_URL }}
      BETTER_AUTH_GOOGLE_CLIENT_ID: ${{ secrets.BETTER_AUTH_GOOGLE_CLIENT_ID }}
      BETTER_AUTH_GOOGLE_CLIENT_SECRET: ${{ secrets.BETTER_AUTH_GOOGLE_CLIENT_SECRET }}
      BETTER_AUTH_GITHUB_CLIENT_ID: ${{ secrets.BETTER_AUTH_GITHUB_CLIENT_ID }}
      BETTER_AUTH_GITHUB_CLIENT_SECRET: ${{ secrets.BETTER_AUTH_GITHUB_CLIENT_SECRET }}
      UPLOADTHING_TOKEN: ${{ secrets.UPLOADTHING_TOKEN }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm build

  container-build:
    name: "Container Build"
    runs-on: ubuntu-latest
    needs: build
    timeout-minutes: 15

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build Image
        id: build_image
        uses: redhat-actions/buildah-build@v2
        with:
          image: ${{ vars.CONTAINER_IMAGE_NAME }}
          tags: ci
          build-args: |
            NEXT_PUBLIC_BASE_URL=${{ vars.NEXT_PUBLIC_BASE_URL }}
          containerfiles: ./Containerfile
